include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/*.g.dart

linter:
  rules:
    always_use_package_imports: true
    avoid_annotating_with_dynamic: true
    prefer_single_quotes: true
    sort_pub_dependencies: true

