name: frontend
description: The Mixology frontend
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  dart_jsonwebtoken: ^2.7.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_web_plugins:
    sdk: flutter
  go_router: ^13.0.0
  http: ^1.0.0
  json_annotation: ^4.8.1
  meta: ^1.8.0
  mutex: ^3.0.1
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  spotify_api: ^1.0.0
  url_launcher: ^6.1.9


dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  test: any


flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
