name: Main
on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  check_format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.x'
          channel: 'stable'
      - name: Check lib formatting
        run: dart format lib --set-exit-if-changed --output=none

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.x'
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
      - name: Run code generation
        run: flutter pub run build_runner build
      - name: Run Analysis
        run: flutter analyze --fatal-infos


  build:
    name: Build Web Package
    runs-on: ubuntu-latest
    needs: [check_format, lint]
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.x'
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
      - name: Run code generation
        run: flutter pub run build_runner build
      - name: Build web package
        run: flutter build web
      - name: Store build result
        uses: actions/upload-artifact@v3
        with:
          name: web-app
          path: build/web

  build_image:
    name: Build Container Image
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main'
    needs: build
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Pull Artifacts
        uses: actions/download-artifact@v3
        with:
          name: web-app
          path: build/web
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the tagged container image
        run: docker build -t ghcr.io/bjoernpetersen/mixology-frontend:${GITHUB_SHA} .
      - name: Push the tagged Docker image
        run: docker push ghcr.io/bjoernpetersen/mixology-frontend:${GITHUB_SHA}

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build_image
    concurrency: production
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Substitute environment variables in values.yaml
        run: "envsubst < values.yaml > values_sub.yaml && mv values_sub.yaml values.yaml"
      - name: Store Kubeconfig
        run: mkdir ~/.kube && printenv "KUBECONFIG" > ~/.kube/config && chmod 400 ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG_RAW }}
      - name: Upgrade helm installation
        run: helm upgrade frontend . --install --namespace=mixology --atomic
