name: Main
on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  check-format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - name: Check lib formatting
        run: dart format lib --set-exit-if-changed --output=none

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - name: Get dependencies
        run: flutter pub get
      - name: Run code generation
        run: dart run build_runner build
      - name: Run Analysis
        run: flutter analyze --fatal-infos

  build-container-image:
    needs:
      - check-format
      - lint
    uses: BjoernPetersen/actions-container/.github/workflows/build-image-kaniko.yml@v3
    with:
      runner-name-build: ubicloud-standard-2-arm
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}

  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    needs:
      - build-container-image
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git push origin main:release

  clean:
    concurrency: cleanup
    needs: [ deploy ]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/clean.yml@v4
